esphome:
  name: joyit_nodemcu_esp32_ex
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "Verhoeckx_glas"
  password: "Goofy2kmacho_99"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Joyit Nodemcu Esp32 Ex"
    password: "PPzHIfjNV92T"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "OTAmacho_99"

ota:
  password: "OTAmacho_99"
